### ISSUE TITLE
how to get download progress when resume

### ISSUE THREAD

**Issue by xuanzhui** [MindorksOpenSource/PRDownloader#102]
Is it able to set `setOnProgressListener` when calling `PRDownloader.resume(downloadId);`?

**Comment by Od1nik** [comment]
KotlinCode:
val downloadId = PRDownloader.download(URL, dir, fileName)
            .build().setOnStartOrResumeListener(object: OnStartOrResumeListener {
                override fun onStartOrResume() {
                    Log.d(TAG, "onStartOrResume")
                }
            })
            .setOnCancelListener(object: OnCancelListener {
                override fun onCancel() {
                    Log.d(TAG, "onCancel")
                }
            })
            .setOnProgressListener(object: OnProgressListener {
                override fun onProgress(progress: Progress?) {
                    val percent = progress!!.currentBytes * 100 / progress.totalBytes

                }
            })

**Comment by Od1nik** [comment]
Kotlin code:
`
val downloadId = PRDownloader.download(URL, dir, fileName)
            .build().setOnStartOrResumeListener(object: OnStartOrResumeListener {
                override fun onStartOrResume() {
                    Log.d(TAG, "onStartOrResume")
                }
            })
            .setOnCancelListener(object: OnCancelListener {
                override fun onCancel() {
                    Log.d(TAG, "onCancel")
                }
            })
            .setOnProgressListener(object: OnProgressListener {
                override fun onProgress(progress: Progress?) {
                    val percent = progress!!.currentBytes * 100 / progress.totalBytes

                }
            })
`

**Comment by Od1nik** [comment]
```kotlin
val downloadId = PRDownloader.download(URL, dir, fileName)
            .build().setOnStartOrResumeListener(object: OnStartOrResumeListener {
                override fun onStartOrResume() {
                    Log.d(TAG, "onStartOrResume")
                }
            })
            .setOnCancelListener(object: OnCancelListener {
                override fun onCancel() {
                    Log.d(TAG, "onCancel")
                }
            })
            .setOnProgressListener(object: OnProgressListener {
                override fun onProgress(progress: Progress?) {
                    val percent = progress!!.currentBytes * 100 / progress.totalBytes

                }
            })
```

**Comment by Od1nik** [comment]
@xuanzhui 
Java code:
```java
downloadIdOne = PRDownloader.download(URL1, dirPath, "facebook.apk")
                        .build()
                        .setOnStartOrResumeListener(new OnStartOrResumeListener() {
                            @Override
                            public void onStartOrResume() {
                                
                            }
                        })
                        .setOnPauseListener(new OnPauseListener() {
                            @Override
                            public void onPause() {
                                
                            }
                        })
                        .setOnCancelListener(new OnCancelListener() {
                            @Override
                            public void onCancel() {
                               
                            }
                        })
                        .setOnProgressListener(new OnProgressListener() {
                            @Override
                            public void onProgress(Progress progress) {
                                
                            }
                        })
                        .start(new OnDownloadListener() {
                            @Override
                            public void onDownloadComplete() {
                                
                            } 
```

**Comment by mihakrajnc** [comment]
@Od1nik I would also like to know this, but I don't think your answer is the solution.

Let's say I start a download, and the app is killed. When the app is restarted, I want to resume the download (assuming I have the database enabled) , which I can do with `PRDownloader.resume(id)`.
But how do I add a listener for that download? If I call `PRDownloader.download`, where I can add the listener, that will start a new download, will it not?

**Comment by mihakrajnc** [comment]
Ahh I see that the download ID is actually a hash made from the url / dirPath / fileName, so it will resume the download that's in the database.

So the answer is correct, starting a "new download" will resume the old one, if you use the same parameters. I assume, at least.

**Comment by xuanzhui** [comment]
Not tested, thanks for your replies.

**Comment by HaiderSaleem** [comment]
> Ahh I see that the download ID is actually a hash made from the url / dirPath / fileName, so it will resume the download that's in the database.
> 
> So the answer is correct, starting a "new download" will resume the old one, if you use the same parameters. I assume, at least.

did it work?
