### ISSUE TITLE
PrDownloader does not work on Android Q Beta 2 build

### ISSUE THREAD

**Issue by rr0055256** [MindorksOpenSource/PRDownloader#107]
I was able to download files until Android Q Beta 1 with PrDownloader. It does not work now. Can you please check?

**Comment by amitshekhariitbhu** [comment]
@rr0055256 okay sure.

**Comment by thatishemanth** [comment]
@rr0055256  Which error you got?

**Comment by rr0055256** [comment]
It works on the Q4 build. I will update, if there is any issue.
