### ISSUE TITLE
support android Q

### ISSUE THREAD

**Issue by ghost1372** [MindorksOpenSource/PRDownloader#119]
hi in android q we cant download file becuase of scoped-storage android q dont let us to create file or folder
so please update this library
https://developer.android.com/preview/privacy/scoped-storage

**Comment by sabrimev** [comment]
Any updates?

**Comment by ghost1372** [comment]
@sabrimev  there is no update but i found a way to fix this problem let me know if you want to know it

**Comment by aashitshah26** [comment]
Hey @ghost1372  can you find anything other than using android:requestLegacyExternalStorage="true" ? if you have please share the solution.

**Comment by ghost1372** [comment]
Hi @aashitshah26 , The only way I found it was to download the files to the application's data folder
to do this i wrote a function Which determines the path of the folder based on the Android version:
```
fun _Path(): String {
        return if (Build.VERSION.SDK_INT >= 29) { // because of new storage privacy in Android >= Q
            externalCacheDir.path + "/my folder/"
        } else {
            "/sdcard/my folder/"
        }
    }
```
