### ISSUE TITLE
com.a.a@5c66bda <<< error in some failed downloads.

### ISSUE THREAD

**Issue by abir-cse** [MindorksOpenSource/PRDownloader#125]
I am downloading some pdf files hosted on Nginx server on Digital Ocean. 
Most of the times it works perfectly. But some users are getting this error [com.a.a@5c66bda]
Can you please explain about com.a.a@5c66bda & how to solve it for them?

**Comment by lucky93agarwal** [comment]
hello sir my name is lucky agarwal.
i'm from india.
sir please reply me
sir download time show error:-
com.downloader.Error@8f6acd

**Comment by lucky93agarwal** [comment]
sir please reply me

**Comment by abircse12** [comment]
I have solved the problem. You need the url Https,  not Http.
