### ISSUE TITLE
Unable to cancel

### ISSUE THREAD

**Issue by karrarkazuya** [MindorksOpenSource/PRDownloader#142]
Downloading works fine but when passing the downloadId returned by PRDownloader.download and attempting to cancel the download request using
PRDownloader.cancel(downloadId);

i get the following
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Object.equals(java.lang.Object)' on a null object reference
        at com.downloader.internal.DownloadRequestQueue.cancel(DownloadRequestQueue.java:100)
        at com.downloader.PRDownloader.cancel(PRDownloader.java:109)

works with tags but not with request ids

**Comment by X1nto** [comment]
Can you share some code? I couldn't get canceling via tag working, I can't use downloadId because I issue a notification on progress bar that will have a button and I can't put a variable there
