### ISSUE TITLE
Download Video

### ISSUE THREAD

**Issue by AdilSattar1233** [MindorksOpenSource/PRDownloader#145]
Not downloading likee app video

**Comment by amitshekhariitbhu** [comment]
@AdilSattar1233 Can you provide me the URL to test?

**Comment by AdilSattar1233** [comment]
Yeah sure ... check it below
https://l.likee.video/v/ClxYIh

**Comment by AdilSattar1233** [comment]
did you test it ??

**Comment by AdilSattar1233** [comment]
I am sill waiting for you response

**Comment by amitshekhariitbhu** [comment]
@AdilSattar1233 The link which you are using is webpage link, not video file link. Do some research on it. If it is a video file URL, it will work.

**Comment by mellowfunk** [comment]
a question??

anyone know how can I download this video https://www.kadgroove.net/watch.php?vid=cd4a48874

regards
