### ISSUE TITLE
total bytes is returning -1 for pdf files

### ISSUE THREAD

**Issue by kayesn786** [MindorksOpenSource/PRDownloader#148]
Hi,
I have pdf files stored in google drive and am exporting them. but totalbytes is returning -1 always

**Comment by alitamoor65** [comment]
I have the same issue files stored on hosting and downloading them with direct download URL. but totalbytes is returning -1 always

**Comment by kayesn786** [comment]
Hi @alitamoor65 ,
Since there was no solution for this, i found another good library https://github.com/tonyofrancis/Fetch
