### ISSUE TITLE
Download Failed (java.io.IOException: Not a directory)

### ISSUE THREAD

**Issue by lokalkart** [MindorksOpenSource/PRDownloader#150]
The logic was working fine with older codes but on implementing PRDownlaoder the exception "java.io.IOException: Not a directory" is thrown in the OnError Method of OnDownloadListener

**Comment by amitshekhariitbhu** [comment]
Please provide the correct path and folder to download with permission.

**Comment by lokalkart** [comment]
@amitshekhariitbhu I did this and the same code is working  fine with thin download manager. I tried a lot to use PR  Download manager but didn't ad eventually this error compelled me to move with ThinDownloadManager.
