### ISSUE TITLE
filename.extension.temp: open failed: ENOENT (No such file or directory)

### ISSUE THREAD

**Issue by abhiint16** [MindorksOpenSource/PRDownloader#152]
I am trying to download a video in SD Card ( **path is :** ./storage/0FEC-3714/Download/PiVideos/Twitter_video_1182020112249.mp4). 

**Getting exception :** /storage/0FEC-3714/Download/PiVideos/Twitter_video_1182020112249.mp4.temp: open failed: ENOENT (No such file or directory)

         `if (!file.exists()) {
                if (file.getParentFile() != null && !file.getParentFile().exists()) {
                    if (file.getParentFile().mkdirs()) {                              **// returning false here.**
                        //noinspection ResultOfMethodCallIgnored
                        file.createNewFile();
                    }
                } else {
                    //noinspection ResultOfMethodCallIgnored
                    file.createNewFile();
                }
            }`

I'm getting the exception at 

`this.outputStream = FileDownloadRandomAccessFile.create(file);` of DownloadTask.java file.

Please tell me If I need some extra permission to download files in SD Card.

**Comment by bshikhar13** [comment]
I am facing the same issue.
