### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by redragon14368** [MindorksOpenSource/PRDownloader#155]
@amitshekhariitbhu
thank-you to provide the code. please update the code with showing download progress on notification

**Comment by abhiint16** [comment]
@redragon14368 you can create your own solution by simply starting a ForegroundService or WorkManager with setForegroundAsync

**Comment by redragon14368** [comment]
> @redragon14368 you can create your own solution by simply starting a ForegroundService or WorkManager with setForegroundAsync

sir can you give it's code, how to do it
