### ISSUE TITLE
How to get download speed

### ISSUE THREAD

**Issue by kalimandal** [MindorksOpenSource/PRDownloader#156]
How to get download speed

**Comment by abhiint16** [comment]
@kalimandal val progress = (progress.currentBytes * 100f / progress.totalBytes).toInt()

**Comment by kalimandal** [comment]
> @kalimandal val progress = (progress.currentBytes * 100f / progress.totalBytes).toInt()

Thanks bro, but I can not understanding this can you explain me please

**Comment by amitshekhariitbhu** [comment]
Not the use-case of the library as of now. If we want to implement this, please refer to [this](https://github.com/facebookarchive/network-connection-class).
