### ISSUE TITLE
Download POST request

### ISSUE THREAD

**Issue by shivasurya** [MindorksOpenSource/PRDownloader#19]
Thanks for the wonderful initiative.

Can this library support download for POST request (response as attachment/deposition) download header types?

Thank you.

**Comment by amitshekhariitbhu** [comment]
@shivasurya you can set header with `setHeader()`.

**Comment by shivasurya** [comment]
I still hoping how to perform POST request method ? any ideas

**Comment by amitshekhariitbhu** [comment]
Currently for that you will have to use this [library](https://github.com/amitshekhariitbhu/Fast-Android-Networking).

**Comment by loyogoy-g** [comment]
How to use setHeader ?

**Comment by dharmesh-om** [comment]
how can i add header or token for downloading file using PRDownloader?
