### ISSUE TITLE
can i get all download process with list

### ISSUE THREAD

**Issue by DeevD** [MindorksOpenSource/PRDownloader#21]
Nice library ..  we can get  all download process are showing on arrrylist

**Comment by amitshekhariitbhu** [comment]
It's doable. We will expose the API in new release.

**Comment by young4983** [comment]
I don't know how to use it in the list. @amitshekhariitbhu

**Comment by aakshansh** [comment]
please provide to some instruction to implement your downloader with any recylcerview or list adapter.....
@amitshekhariitbhu 
and thanks for your open source codes

**Comment by demo-Ashif** [comment]
please provide some instruction to implement your downloader with any recylcerview or list adapter.....
@amitshekhariitbhu 

commenting same as @aakshansh because i need that guideline

**Comment by amitshekhariitbhu** [comment]
for recyclerview, check this https://github.com/MindorksOpenSource/PRDownloader/issues/158
