### ISSUE TITLE
is it possible to know the name of the file on the disk while downloading ?

### ISSUE THREAD

**Issue by gulzar1996** [MindorksOpenSource/PRDownloader#23]
I am trying to implement caching and streaming of video using this library.
I do this by downloading the video file and give it a filename. But when downloading it has a different file name so i am unable to access the file during download. But when the download is successful I get it automatically renamed.

**Comment by amitshekhariitbhu** [comment]
The temp file name is `actualname+".temp"`. Example: `image.png.temp`
