### ISSUE TITLE
App freeezing

### ISSUE THREAD

**Issue by osinakayah** [MindorksOpenSource/PRDownloader#24]
It makes the button on my application screen to stop working

**Comment by Aiuspaktyn** [comment]
I have the same problem

**Comment by amitshekhariitbhu** [comment]
@osinakayah  @Aiuspaktyn Can u provide me the more detail. Please also look into the sample app. Any step to reproduce it in the sample app.

**Comment by Aiuspaktyn** [comment]
Resolved using DEFAULT_MAX_NUM_THREADS = 1 in DefaultExecutorSupplier

**Comment by litchicoder** [comment]
I have the same problem
