### ISSUE TITLE
Getting progress.totalBytes value as -1

### ISSUE THREAD

**Issue by rohan2817** [MindorksOpenSource/PRDownloader#25]
I am facing an issue while working with this library, in callback `onProgress(Progress progress)` getting the value of `progress.totalBytes` as -1. 

But the `progress.currentBytes` value is okay and also the download is working as expected.

Any idea why this is happening?

**Comment by amitshekhariitbhu** [comment]
This means server is not sending the content length.

**Comment by rohan2817** [comment]
Got it, Thanks 👍
