### ISSUE TITLE
Resume Download

### ISSUE THREAD

**Issue by arsenal2323** [MindorksOpenSource/PRDownloader#27]
Hi,
How to resume download after closing app (destroying activity ) and opening it again?

**Comment by arsenal2323** [comment]
Ok, Thank you

**Comment by zeero0** [comment]
If we pass same **url** and **path** again if the download is **running** then download is **restarted** and error occurs at the end which deletes file from storage.
Is there a way to continue download without restarting?

**Comment by amitshekhariitbhu** [comment]
@zeero0 let me debug this once.
