### ISSUE TITLE
Question about corePoolSize value.

### ISSUE THREAD

**Issue by nichbar** [MindorksOpenSource/PRDownloader#28]
Hi, I've been learning how to write a download library these days.
PRDownloader is nice, but codes written below confuse me.
https://github.com/MindorksOpenSource/PRDownloader/blob/6cc02b41443ed052a36e36d9c02e3ab32e10ca9f/prdownloader/src/main/java/com/downloader/core/DownloadExecutor.java#L34-L35
Setting the same value to corePoolSize and maximumPoolSize is not efficient , i think.
As reference, OkHttp do set corePoolSize to zero and maximumPoolSize to `Interge.MAX_VALUE`.
[OkHttp Dispatcher](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/Dispatcher.java#L65-L66)

**Comment by amitshekhariitbhu** [comment]
It depends on choice. Check fresco library.
