### ISSUE TITLE
download stop when enable progurd

### ISSUE THREAD

**Issue by articgram** [MindorksOpenSource/PRDownloader#39]
when i enable progurd 
the realize apk has many error in downloading
but when peogurd is disabled problem solved
i ahould enable progurd for security
help me please .

**Comment by amitshekhariitbhu** [comment]
Sorry for the delay. I have fixed the release mode issue. Please try the updated library and confirm me.

`compile 'com.mindorks.android:prdownloader:0.3.0'`
