### ISSUE TITLE
Working With Fragments

### ISSUE THREAD

**Issue by peace-shillong** [MindorksOpenSource/PRDownloader#50]
This is more of a Question than an issue.
I'm working with Fragments and using this library in one fragment(downloads), 
I'm handling download/pause button clicks inside an Adapter Class, If I download a file it displays the progressbar and filesize correctly, but if I go to another fragment and return back to the downloads fragment the progressbar is gone and also the pause button is now displayed as start download button.
Is there any way to tell if I'm in the downloads fragment any not reset the layout of the fragment or can we use a background service with the library and maybe instead of displaying the information on the Screen, we will display the download progress in the notification area.

**Comment by ninonur** [comment]
Same issue here, whenever I switch between fragment the status return UNKNOWN. I think it because the integer that handle the request was trigger again when fragment respawn, so I make it as static in another class and load it using get and set. But it doesn't work -_-

**Comment by X1nto** [comment]
Well, I know I'm late to the party but I solved the issue by moving downloader to the service and sending progress through LocalBroadcast. Solution is not ideal but it works, although seems like that exiting the app will pause the downloader, but switching fragments won't be a problem
