### ISSUE TITLE
What does it mean by isConnectionError ??

### ISSUE THREAD

**Issue by ifty-rahman** [MindorksOpenSource/PRDownloader#84]
I implemented the library by following the code in description but I am getting error ( isConnectionError() = true, isServerError() = false ).

As I see there is no throwable or message in error, how can I fix this? My device is connected to internet and the server is up and also the app is handing other network based work successfully. So how can I make this library work??

**Comment by amitshekhariitbhu** [comment]
Have you given the read/write permission?

**Comment by ifty-rahman** [comment]
My app do have external storage read and write permission and I confirmed it with requestPermissions.

**Comment by Tobibur** [comment]
@ifty-rahman I had the same issue but when I checked properly, my download storage path had the file name on it too i.e,
```kotlin
fun getDownloadPath(): String {
        val file = File(
            Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS).toString()
                    + File.separator + "FolderName" + File.separator + "FILENAME.mp4"
        )

        return file.absolutePath
    }
```

But we are already sending the file name in the DownloadRequestBuilder:
```kotlin
downloadID = PRDownloader.download(Utils.downloadUrl, Utils.getDownloadPath(), "FILENAME.mp4")
            .build()
```

Removing the first solved it. Hope it helps maybe. 😃

**Comment by getyoteamsolutions** [comment]
I got the same issue while download, OnDownloadListener->onError give me an error
I found that I send file name ""(empty) to downloader that's why it give me this error.
![Untitled](https://user-images.githubusercontent.com/49678167/58364825-7eaf5900-7ed7-11e9-9055-66e9f939ecdf.png)

**Comment by amitshekhariitbhu** [comment]
I will add the error message which explains correctly the exact error in the upcoming release.

**Comment by HamzaMaqsood04** [comment]
does someone has found the solution?

**Comment by HamzaMaqsood04** [comment]
This library have too much bugs in it & we can't find it easily.

**Comment by amitshekhariitbhu** [comment]
Mostly it will be file permissions issue, as I said above we will update the library. Not updated till now, because it was not in priority list. I will check the requested issues and update it accordingly. One PR is pending, that will be reviewed and merged in update too.

**Comment by amitshekhariitbhu** [comment]
However file permissions must be handled at app end. Library should just throw error.

**Comment by HamzaMaqsood04** [comment]
Sir downloading is working on some devices but not working on all. Some Devices gives error

**Comment by HamzaMaqsood04** [comment]
Sir downloading is working on some devices but not working on all. Some Devices gives error

**Comment by amitshekhariitbhu** [comment]
@HamzaMaqsood04 I will help with that. Can you please tell us more about the Device, Android Version and etc? I will check accordingly.

**Comment by HamzaMaqsood04** [comment]
Galaxy A10
Android version 10

**Comment by HamzaMaqsood04** [comment]
However i have solved this issue. Hoping this library updates background downloading , notification & message on complete in future.

**Comment by amitshekhariitbhu** [comment]
Yes, these new features, we can plan.

**Comment by HamzaMaqsood04** [comment]
thanks alot so nice of you brother

**Comment by sheinin** [comment]
> However i have solved this issue. Hoping this library updates background downloading , notification & message on complete in future.

May you provide the solution?

**Comment by HamzaMaqsood04** [comment]
I am extremely sorry for late reply .I have just handle permissions on different side of android version. Although downloading is not running at background services.
